name: remote_logging
description: Sending Logger() messages to loggly.com
version: 1.1.0
homepage: https://github.com/justprodev/flutter_remote_logging.git

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http:
  logging:

dev_dependencies:
  flutter_lints:
  test:
  fake_http_client: ^1.0.0